
export const EXERCISE_CATEGORIES = [
  "RUTINA DE PECHO",
  "RUTINA DE PIERNA",
  "RUTINA DE BICEPS",
  "RUTINA DE TRICEPS",
  "RUTINA DE ESPALDA",
  "RUTINA DE HOMBRO",
  "RUTINA DE FEMORALES Y GLUTEO"
] as const;

export const EXERCISE_BANK: Record<string, string[]> = {
  "RUTINA DE PECHO": [
    "PRESS INCLINADO CON BARRA", "PRESS INCLINADO CON MANCUERNAS", "PRESS INCLINADO CERRADO CON MANCUERNAS",
    "PRESS PLANO CON BARRA", "PRESS PLANO CON MANCUERNAS", "PRESS EN APARATO", "PRESS EN APARATO LATERAL",
    "APERTURAS CON MANCUERNAS HORIZONTAL", "APERTURAS CON MANCUERNA INCLINADO", "APERTURAS INCLINADAS CON CABLE",
    "APERTURAS HORIZONTAL CON CABLE", "APERTURAS EN PEC FLY", "CRUCE DE POLEAS ALTO", "CRUCE DE POLEAS MEDIO",
    "CRUCE DE POLEAS BAJO", "PULL OVER CON MANCUERNA", "FONDOS EN PARALELAS PARA PECHO", "LAGARTIJAS NORMALES",
    "LAGARTIJAS CON PIES ARRIBA", "LAGARTIJAS CERRADAS", "ELEVACION FRONTAL CON DISCO", "CRUCE FRONTAL CON MANCUERNAS"
  ],
  "RUTINA DE PIERNA": [
    "SENTADILLA LIBRE NORMAL", "SENTADILLA LIBRE FRONTAL", "SENTADILLA HACK NORMAL", "SENTADILLA HACK CERRADA",
    "SENTADILLA PERFECTA NORMAL", "SENTADILLA PERFECTA CERRADA", "SENTADILLA CON MANCUERNAS", "SENTADILLA ZIZZY",
    "SENTADILLA ZIZZY LENTA Y RAPIDA", "SENTADILLA ZIZZY 2 PESOS", "PRENSA NEGRA ESTANDAR", "PRENSA NEGRA PIES ESTRECHOS",
    "PRENSA NEGRA PIES BAJOS", "PRENSA NEGRA A 1 PIE ESTANDAR", "EXTENSION SENTADO", "EXTENSION SENTADO 2 PESOS",
    "EXTENSION SENTADO A 1 PIERNA", "EXTENSION SENTADO 4X4X4", "DESPLANTES BULGAROS CON BARRA",
    "DESPLANTES BULGAROS CON MANCUERNAS", "DESPLANTES FIJOS CON BARRA", "DESPLANTES FIJOS CON MANCUERNAS"
  ],
  "RUTINA DE BICEPS": [
    "PREDICADOR CON BARRA Z", "PREDICADOR CON MANCUERNAS", "PREDICADOR CON BARRA SEMI OLIMPICA", "PREDICADOR EN APARATO",
    "MARTILLOS EN BANCO PREDICADOR", "CURL CON MANCUERNAS DE PIE", "CURL CON BARRA OLIMPICA DE PIE", "CURL CON BARRA Z DE PIE",
    "CURL CON MANCUERNAS EN BANCO INCLINADO", "MARTILLOS CON MANCUERNA DE PIE", "MARTILLOS CON MANCUERNA EN BANCO INCLINADO",
    "MARTILLOS DE PIE con cuerda en polea", "CURL EN BANCO INCLINADO CON MANERAL RECTO", "CURL DE PIE CON MANERAL Z",
    "CURL DE PIE CON MANERAL RECTO CHICO", "CURL INVERTIDO CON BARRA Z", "BICEPS POLEA ALTA A 1 MANO", "CURL SPIDER CON BARRA Z",
    "CURL SPIDER CON BARRA SEMI OLIMPICA", "CURL SPIDER CON MANCUERNAS", "CURL PREEXAUSTIVO CON MANCUERNAS", "CURL PREEXAUSTIVO CON BARRA Z"
  ],
  "RUTINA DE TRICEPS": [
    "PRES FRANCES CON BARRA Z", "PRES FRANCES CON BARRA SEMI OLIMPICA", "PRES FRANCES CON MANCUERNAS", "PUSH DOWN CON TRIANGULO",
    "PUSH DOWN CON BARRA RECTA CHICA", "PUSH DOWN CON CUERDA", "PUSH DOWN CON MANERAL A 1 MANO", "PUSH DOWN INVERTIDO",
    "EXTENSION CON TRIANGULO", "EXTENSION CON MANERAL RECTO CHICO", "PATADA DE MULA CON MANCUERNAS", "PATADA DE MULA CON CUERDA",
    "PATADA DE MULA CON CABLE", "PRES COPA CON 2 MANOS", "PRES COPA A 1 MANO", "FONDOS ENTRE BANCOS", "FONDOS EN PARALELAS", "FONDOS EN APARATO"
  ],
  "RUTINA DE ESPALDA": [
    "DOMINADAS PRONO", "DOMINADAS CERRADAS", "DOMINADAS CON TRIANGULO", "JALON AL PECHO CON MANERAL TIPO 'D'", "DOMINADAS SUPINO",
    "JALON FRONTAL PRONO", "JALON TRAS NUCA", "JALON FRONTAL CERRADO PRONO", "JALON SUPINO", "JALON AL PECHO CON TRIANGULO",
    "REMO CON BARRA PRONO", "REMO CON BARRA SUPINO", "REMO CON BARRA Y TRIANGULO", "REMO CON BARRA A UNA MANO", "REMO CON MANCUERNA PRONO",
    "REMO CON MANCUERNA NEUTRO", "REMO CON MANCUERNA EN BANCO INCLINADO", "REMO EN APARATO HAMMER PRONO", "REMO EN APARATO HAMMER CERRADO",
    "REMO INDIVIDUAL CON CABLE", "REMO INCADO CON POLEAS INDIVIDUAL", "REMO SENTADO CON TRIANGULO EN APARATO", "REMO SENTADO PRONO",
    "REMO SENTADO SUPINO", "PULL OVER DE PIE CON POLEAS (BARRA CHICA)", "PULL OVER ACOSTADO CON MANCUERNAS", "PULL OVER ACOSTADO CON BARRA Z",
    "PULL DOWN CON CUERDA NEGRA", "BUENOS DIAS CON BARRA OLIMPICA", "HIPER EXTENSION", "JALON ISOLATERAL", "REMO DOBLE EN POLEAS CON CABLE"
  ],
  "RUTINA DE HOMBRO": [
    "PRESS MILITAR CON BARRA SENTADO", "PRESS MILITAR TRAS NUCA CON BARRA SENTADO", "PRESS MILITAR SENTADO EN APARATO HAMMER",
    "PRESS MILITAR SENTADO CON MANCUERNAS", "PRESS ARNOLD SENTADO CON MANCUERNAS", "ELEVACION FRONTAL CON MANCUERNAS",
    "ELEVACION FRONTAL CON DISCO", "ELEVACION FRONTAL CON BARRA", "ELEVACION FRONTAL CON BARRA Z EN POLEA",
    "ELEVACION LATERAL CON MANCUERNAS", "ELEVACION POSTERIOR CON MANCUERNAS", "CRUCE DE POLEAS ALTO", "CRUCE D EPOLEAS VAJO",
    "EXTENSION LATERAL CON CABLE", "EXTENSION LATERAL EN PEC FLY", "REMO DE PIE CON DISCO", "REMO DE PIE CON BARRA Z",
    "REMO DE PIE CON MANCUERNAS LATERALES", "PULL FACE CON CUERDA NEGRA", "PULL FACE ALTO CON CUERDA NEGRA",
    "ELEV. FRONTAL EN BANCO INCLINADO INC.", "ELEV. FRONTAL CON BARRA EN BANC INC."
  ],
  "RUTINA DE FEMORALES Y GLUTEO": [
    "SENTADILLA LIBRE NORMAL", "SENTADILLA LIBRE ABIERTA", "SENTADILLA HACK ABIERTA", "SENTADILLA HACK INVERTIDA",
    "SENTADILLA PERFECTA INVERTIDA", "SENTADILLA PERFECTA PIES ABIERTOS", "SENTADILLA TIPO SUMO CON MANCUERNAS",
    "SENTADILLA TIPO SUMO CON BARRA", "SENTADILLA TIPO JEFFERSON", "SENTADILLA LANDMINE", "PESO MUERTO RUMANO (RIGIDO)",
    "PESO MUERTO CON MANCUERNAS RUMANO", "PESO MUERTO TRADICIONAL O FLEXIONANDO", "PESO MUERTO TIPO SUMO CON BARRA",
    "PESO MUERTO CON MANCUERNAS A 1 PIERNA", "PRENSA ROJA CERRADA", "PRENSA ROJA NORMAL", "PRENSA ROJA ABIERTA",
    "CURL ACOSTADO", "CURL ACOSTADO 2 PESOS", "CURL ACOSTADO A 1 PIERNA", "CURL ACOSTADO 4X4X4", "CURL CONCENTRADO",
    "CURL CONCENTRADO 2 PESOS", "ABDUCTORES (ABRIENDO)", "ADUCTORES (CERRANDO)", "DESPLANTES CAMINANDO CON MANCUERNAS",
    "DESPLANTES CAMINANDO CON BARRA", "PUENTES CON BARRA", "PUENTES CON BARRA A 1 PIERNA", "PUENTES CON MANCUERNAS",
    "RANITAS EN BANCO ACOSTADA", "HIPEREXTENSION"
  ]
};
